#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path
from typing import Any


class ToolError(Exception):
    pass


def fmt_ts(seconds: float) -> str:
    total = max(0, int(round(seconds)))
    h = total // 3600
    m = (total % 3600) // 60
    s = total % 60
    return f"{h:02d}:{m:02d}:{s:02d}"


def render_compact(segments: list[dict[str, Any]]) -> list[dict[str, Any]]:
    if not segments:
        return []
    merged = [dict(segments[0])]
    for seg in segments[1:]:
        last = merged[-1]
        if seg.get("display_speaker") == last.get("display_speaker") and seg.get("start", 0) <= last.get("end", 0) + 1.0:
            last["end"] = max(last.get("end", 0), seg.get("end", 0))
            last["text"] = (last.get("text", "") + " " + seg.get("text", "")).strip()
        else:
            merged.append(dict(seg))
    return merged


def main() -> int:
    parser = argparse.ArgumentParser(description="Render meeting2json output into Markdown transcript.")
    parser.add_argument("input", help="Path to transcript JSON")
    parser.add_argument("--output", help="Output markdown path (default: <input>.md)")
    parser.add_argument("--title", default="Meeting transcript")
    parser.add_argument("--compact", action="store_true", help="Merge nearby consecutive segments by same speaker")
    args = parser.parse_args()

    try:
        in_path = Path(args.input)
        if not in_path.exists():
            raise ToolError(f"Input JSON not found: {in_path}")

        try:
            data = json.loads(in_path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001
            raise ToolError(f"Failed to read JSON: {exc}") from exc

        segments = data.get("segments") or []
        if args.compact:
            segments = render_compact(segments)

        source_name = (data.get("input") or {}).get("filename", "unknown")
        model = (data.get("settings") or {}).get("model", "unknown")
        language = (data.get("settings") or {}).get("language", "unknown")
        duration = (data.get("input") or {}).get("duration_seconds", 0)
        num_chunks = (data.get("processing") or {}).get("num_chunks", "?")
        generator = (data.get("tool") or {}).get("name", "meeting2json.py")

        lines: list[str] = []
        lines.append(f"# {args.title}")
        lines.append("")
        lines.append(f"- Source file: {source_name}")
        lines.append(f"- Model: {model}")
        lines.append(f"- Language: {language}")
        lines.append(f"- Duration: {fmt_ts(float(duration or 0))}")
        lines.append(f"- Chunks: {num_chunks}")
        lines.append(f"- Generated by: {generator}.py")
        lines.append("")
        lines.append("## Transcript")
        lines.append("")

        for seg in segments:
            start = fmt_ts(float(seg.get("start", 0)))
            end = fmt_ts(float(seg.get("end", seg.get("start", 0))))
            speaker = seg.get("display_speaker") or seg.get("speaker") or "Speaker"
            text = str(seg.get("text", "")).strip()
            if not text:
                continue
            lines.append(f"**[{start} - {end}] {speaker}**  ")
            lines.append(text)
            lines.append("")

        output_path = Path(args.output) if args.output else in_path.with_suffix(".md")
        try:
            output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        except Exception as exc:  # noqa: BLE001
            raise ToolError(f"Failed to write Markdown output: {exc}") from exc

        print(f"Wrote Markdown transcript: {output_path}")
        return 0

    except ToolError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
